export const TAROT_CARDS = [
  {
    name: "The Fool",
    arcana: "major",
    suit: null,
    line: "A first step is already behind you.",
    narrative: "You stepped off the known path before the map was finished. The drop looks steep because you are still glancing back at the cliff.",
  },
  {
    name: "The Magician",
    arcana: "major",
    suit: null,
    line: "The means are in your hands.",
    narrative: "Skill, word, will, and the thing in front of you are already on the table. Use one of them instead of arranging the tools again.",
  },
  {
    name: "The High Priestess",
    arcana: "major",
    suit: null,
    line: "A quiet knowing asks you to listen.",
    narrative: "A fact you already noticed is waiting behind the noise, still unspoken. Sit with it long enough to hear the sentence it is trying to finish.",
  },
  {
    name: "The Empress",
    arcana: "major",
    suit: null,
    line: "Care and growth are asking for room.",
    narrative: "Something living wants time, food, and a little less hurry. Water it, leave it space, and do not pull it up to check the roots.",
  },
  {
    name: "The Emperor",
    arcana: "major",
    suit: null,
    line: "Order holds when you choose it.",
    narrative: "A boundary you set on purpose can hold a whole day together. Choose the rule, keep it, and let other people see where the line is.",
  },
  {
    name: "The Hierophant",
    arcana: "major",
    suit: null,
    line: "A trusted form can still teach you.",
    narrative: "An old practice or a teacher still has a use if you enter it awake. Take the part that steadies you and leave the part that only repeats.",
  },
  {
    name: "The Lovers",
    arcana: "major",
    suit: null,
    line: "A choice of the heart is in front of you.",
    narrative: "Two roads are real, and wanting both will not walk either of them. Name the one that still feels like you when the room is quiet.",
  },
  {
    name: "The Chariot",
    arcana: "major",
    suit: null,
    line: "Will and direction can carry you through.",
    narrative: "Two pulls are yoked to the same cart, and they will not agree on their own. Point them at one destination and keep your hands on the reins.",
  },
  {
    name: "Strength",
    arcana: "major",
    suit: null,
    line: "Gentle courage outlasts a hard grip.",
    narrative: "The hard thing does not need to be crushed. A steady hand and a calm voice last longer than force.",
  },
  {
    name: "The Hermit",
    arcana: "major",
    suit: null,
    line: "A lamp of your own is enough for this road.",
    narrative: "You do not need a crowd to see the next few steps. Carry a small light and let the path show itself one stone at a time.",
  },
  {
    name: "Wheel of Fortune",
    arcana: "major",
    suit: null,
    line: "The turn is already in motion.",
    narrative: "The wheel has moved whether you voted for it or not. Notice which way it turns, and place your feet for the next rise.",
  },
  {
    name: "Justice",
    arcana: "major",
    suit: null,
    line: "A fair weight is being set.",
    narrative: "Cause and result are lining up in plain sight. Tell the truth about your part, then accept the measure that follows.",
  },
  {
    name: "The Hanged Man",
    arcana: "major",
    suit: null,
    line: "A pause shows what rushing hides.",
    narrative: "You are hung between an old view and a new one, and struggling only tightens the knot. Stay still until the picture turns and makes sense.",
  },
  {
    name: "Death",
    arcana: "major",
    suit: null,
    line: "One chapter closes so another can open.",
    narrative: "A season has ended, even if you are still holding the last page. Let the ending be complete so the next room can open.",
  },
  {
    name: "Temperance",
    arcana: "major",
    suit: null,
    line: "Measure and mix until it steadies.",
    narrative: "Two strong things need to be poured together a little at a time. The slow pace is what keeps the mix from splitting.",
  },
  {
    name: "The Devil",
    arcana: "major",
    suit: null,
    line: "A chain stays only while you hold it.",
    narrative: "The loop feels locked, yet the clasp is in your own hand. Name the habit, the bargain, or the fear, and the chain gets lighter.",
  },
  {
    name: "The Tower",
    arcana: "major",
    suit: null,
    line: "A false structure is coming down.",
    narrative: "A building that was never true is cracking, and bracing it will not make it honest. Let the false part fall so you can see the ground again.",
  },
  {
    name: "The Star",
    arcana: "major",
    suit: null,
    line: "A clear hope holds if you keep going.",
    narrative: "After the shock, a quiet hope is still there, small and specific. Keep walking toward it. It does not need to be loud to be real.",
  },
  {
    name: "The Moon",
    arcana: "major",
    suit: null,
    line: "The path is dim, so go by what you trust.",
    narrative: "Shapes on this road look larger than they will in daylight. Move by the landmarks you already trust, and leave the rest until morning.",
  },
  {
    name: "The Sun",
    arcana: "major",
    suit: null,
    line: "Plain joy is allowed to be simple.",
    narrative: "The day is bright enough to see things as they are, and some of them are simply good. Take the warmth without turning it into a test.",
  },
  {
    name: "Judgement",
    arcana: "major",
    suit: null,
    line: "An old call is ready for an answer.",
    narrative: "A past choice is rising and asking what you will do with it now. Answer it cleanly. You do not have to stay inside the old story.",
  },
  {
    name: "The World",
    arcana: "major",
    suit: null,
    line: "A cycle completes and leaves you whole.",
    narrative: "A long loop is closing, and the work of it is done enough to step through. The next cycle can start from a finished one.",
  },
  {
    name: "Ace of Wands",
    arcana: "minor",
    suit: "wands",
    line: "A new effort wants a first move.",
    narrative: "A spark has landed in dry grass. Give it a task today, before it burns out as a mood.",
  },
  {
    name: "Two of Wands",
    arcana: "minor",
    suit: "wands",
    line: "A plan is waiting for a direction.",
    narrative: "You can see farther than your feet have gone. Pick one horizon and stop scanning all of them.",
  },
  {
    name: "Three of Wands",
    arcana: "minor",
    suit: "wands",
    line: "What you sent out is coming back in view.",
    narrative: "The ships are already out. Watch the water, and do not launch another before these return.",
  },
  {
    name: "Four of Wands",
    arcana: "minor",
    suit: "wands",
    line: "A pause to mark what already stands.",
    narrative: "The frame is up and people are gathering under it. Stop building for a moment and let the celebration count.",
  },
  {
    name: "Five of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Several aims are knocking into each other.",
    narrative: "Everyone has a stick and nobody has agreed on the game. Step back until you can see which contest is actually yours.",
  },
  {
    name: "Six of Wands",
    arcana: "minor",
    suit: "wands",
    line: "A public win asks you to keep your footing.",
    narrative: "The crowd is cheering a win you earned. Take the praise, then keep your balance so the next mile stays yours.",
  },
  {
    name: "Seven of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Hold the ground you already earned.",
    narrative: "You are on the high ground while others climb. You do not have to win every argument. Keep the hill that matters.",
  },
  {
    name: "Eight of Wands",
    arcana: "minor",
    suit: "wands",
    line: "News and motion arrive close together.",
    narrative: "Messages, travel, and decisions are arriving in a bunch. Clear the path so they can pass instead of stacking up.",
  },
  {
    name: "Nine of Wands",
    arcana: "minor",
    suit: "wands",
    line: "You are tired, and still standing.",
    narrative: "You have been hit before and you are still at the post. Rest your weight on the staff. Vigilance is not the same as panic.",
  },
  {
    name: "Ten of Wands",
    arcana: "minor",
    suit: "wands",
    line: "The load is real, and it is yours to set down.",
    narrative: "The bundle is heavy because you picked up every stick. Set down the ones that were never your errand.",
  },
  {
    name: "Page of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Curiosity is looking for a trial.",
    narrative: "A beginner's fire is looking for a safe place to practice. Try the small experiment before you announce the vocation.",
  },
  {
    name: "Knight of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Move while the heat is honest.",
    narrative: "The horse is already moving. Ride while the aim is clear, and do not set fire to the places you still need.",
  },
  {
    name: "Queen of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Steady fire can warm a whole room.",
    narrative: "You can hold a room without shouting. Warmth and a straight back will do more than a flare.",
  },
  {
    name: "King of Wands",
    arcana: "minor",
    suit: "wands",
    line: "Lead the work without losing the spark.",
    narrative: "Vision has a schedule now. Point people at the work, keep the flame, and do not confuse heat with leadership.",
  },
  {
    name: "Ace of Cups",
    arcana: "minor",
    suit: "cups",
    line: "A feeling is opening that you can answer.",
    narrative: "A full cup is being offered. You can drink, or you can keep your hands in your pockets. The offer will not wait forever.",
  },
  {
    name: "Two of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Two people meet on even ground.",
    narrative: "Two cups meet in the middle. This is a pact of equals, not a rescue. Meet the other person where you both can stand.",
  },
  {
    name: "Three of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Shared joy is part of the news.",
    narrative: "Friends are lifting cups for something that already happened. Join the circle. Joy that is shared stays longer.",
  },
  {
    name: "Four of Cups",
    arcana: "minor",
    suit: "cups",
    line: "A gift is here, and you have not looked yet.",
    narrative: "You are staring at three cups and missing the one at your elbow. Look sideways before you decide nothing is here.",
  },
  {
    name: "Five of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Grief is looking at what spilled.",
    narrative: "Two cups are still standing behind the ones that fell. Grief can have the front of the room. Do not forget what remains.",
  },
  {
    name: "Six of Cups",
    arcana: "minor",
    suit: "cups",
    line: "An old kindness still has a use.",
    narrative: "A younger self hands you a cup from an earlier house. The memory is offering comfort, not a demand to move back in.",
  },
  {
    name: "Seven of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Too many wishes are blurring the real one.",
    narrative: "Seven cups float, and most of them are vapor. Pick the one you can actually hold, and let the glittering rest dissolve.",
  },
  {
    name: "Eight of Cups",
    arcana: "minor",
    suit: "cups",
    line: "You can leave what no longer feeds you.",
    narrative: "You are walking away from a neat stack of cups under the moon. The leaving is the point. What you need is not in that pile.",
  },
  {
    name: "Nine of Cups",
    arcana: "minor",
    suit: "cups",
    line: "A plain wish is close enough to enjoy.",
    narrative: "The wish you named is sitting in front of you, ordinary and satisfied. Enjoy it before you order a larger one.",
  },
  {
    name: "Ten of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Belonging is the quiet part of the picture.",
    narrative: "A household stands under a rainbow of cups. Belonging here is made of daily gestures, not one perfect scene.",
  },
  {
    name: "Page of Cups",
    arcana: "minor",
    suit: "cups",
    line: "A soft message is worth taking seriously.",
    narrative: "A small cup holds a surprise you did not expect. Treat the odd, tender message as real enough to answer.",
  },
  {
    name: "Knight of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Follow the feeling, then check the road.",
    narrative: "The rider offers a cup while the horse keeps moving. The promise is sincere, and it still needs a road that exists.",
  },
  {
    name: "Queen of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Care without losing the edge of yourself.",
    narrative: "The cup she holds is deep, and she does not spill it to prove it is full. Feel fully, and keep a shore.",
  },
  {
    name: "King of Cups",
    arcana: "minor",
    suit: "cups",
    line: "Feeling can stay calm and still decide.",
    narrative: "Still water can carry a decision. He feels the current and does not let it steer the boat alone.",
  },
  {
    name: "Ace of Swords",
    arcana: "minor",
    suit: "swords",
    line: "A clear idea cuts through the noise.",
    narrative: "A blade stands upright in a clear sky. One true sentence can cut a knot that weeks of talk only tightened.",
  },
  {
    name: "Two of Swords",
    arcana: "minor",
    suit: "swords",
    line: "A choice is waiting behind a closed eye.",
    narrative: "Two swords stay crossed in front of a blindfold. The stalemate protects you from choosing. Take the cloth off when you are ready to see.",
  },
  {
    name: "Three of Swords",
    arcana: "minor",
    suit: "swords",
    line: "The hurt is named, so it can mend.",
    narrative: "The pain is specific, and the weather around it is honest. Naming it is how the rain starts to pass.",
  },
  {
    name: "Four of Swords",
    arcana: "minor",
    suit: "swords",
    line: "Rest is part of the work.",
    narrative: "A body rests in a quiet room while the swords wait outside. Sleep or a closed door is how the mind puts the blades down.",
  },
  {
    name: "Five of Swords",
    arcana: "minor",
    suit: "swords",
    line: "A win that costs the room is still a loss.",
    narrative: "The blades are gathered from people who left the field. If the victory emptied the camp, ask what you actually won.",
  },
  {
    name: "Six of Swords",
    arcana: "minor",
    suit: "swords",
    line: "Leaving the rough water is already progress.",
    narrative: "A boat is leaving a rough shore for a smoother one. You do not have to love the leaving. You only have to stay in the boat.",
  },
  {
    name: "Seven of Swords",
    arcana: "minor",
    suit: "swords",
    line: "A shortcut is hiding a later cost.",
    narrative: "Someone slips away with an armful of blades. A clever exit can steal from your own future. Check what you are carrying out.",
  },
  {
    name: "Eight of Swords",
    arcana: "minor",
    suit: "swords",
    line: "The bind is tighter in the story than in the facts.",
    narrative: "The cage is a ring of thoughts you can test. Try one step. The circle is wider than it looks.",
  },
  {
    name: "Nine of Swords",
    arcana: "minor",
    suit: "swords",
    line: "The night is louder than the morning will be.",
    narrative: "You wake in the dark with worries lined up on the wall. The mind is rehearsing pain that has not arrived. Morning will shrink most of it.",
  },
  {
    name: "Ten of Swords",
    arcana: "minor",
    suit: "swords",
    line: "An ending has finished; stop adding to it.",
    narrative: "The worst of this story has already happened. There is nothing useful in adding another blow. The light at the edge of the sky is dawn.",
  },
  {
    name: "Page of Swords",
    arcana: "minor",
    suit: "swords",
    line: "Questions are sharper than answers right now.",
    narrative: "A youth holds a sword the way someone else would hold a question. Look, ask, and do not swing until you know what you are cutting.",
  },
  {
    name: "Knight of Swords",
    arcana: "minor",
    suit: "swords",
    line: "Speed is useful only if the aim is true.",
    narrative: "The charge goes forward with the blade first. Speed serves you when the target is real. If it is not, you are only making wind.",
  },
  {
    name: "Queen of Swords",
    arcana: "minor",
    suit: "swords",
    line: "See it plainly, then speak once.",
    narrative: "She looks down the edge of the sword and speaks after she has seen. Clarity is the kindness. Extra words are not.",
  },
  {
    name: "King of Swords",
    arcana: "minor",
    suit: "swords",
    line: "A firm judgment still needs a fair ear.",
    narrative: "The throne is stone and the sword is a rule. Judge from evidence, and leave a chair in the room for a fact you do not like.",
  },
  {
    name: "Ace of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "A practical chance is in your hand.",
    narrative: "A coin sits in an open hand at a garden gate. Work, money, or a body that can start is actually here. Take hold of it.",
  },
  {
    name: "Two of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Two duties can share one rhythm.",
    narrative: "Two coins loop while the sea keeps moving. You can keep both duties if you let them take turns. A rigid balance will drop one.",
  },
  {
    name: "Three of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Skill grows when the work is shared.",
    narrative: "Three workers raise one plan together. The craft gets better when you let other skilled hands touch it.",
  },
  {
    name: "Four of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Holding tight can block the next coin.",
    narrative: "Coins are clutched to the chest and pinned under the feet. Safety has turned into a grip. Loosen one hand so something new can land.",
  },
  {
    name: "Five of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Help is nearer than the cold suggests.",
    narrative: "Two figures pass a lit window in the snow. The hardship is real, and so is the door with light behind it. Ask, or go in.",
  },
  {
    name: "Six of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Give and receive on a scale you can see.",
    narrative: "Coins are weighed into waiting hands. Fair exchange has a visible scale. Give what you can see, and receive without disappearing.",
  },
  {
    name: "Seven of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "The crop is slow; look before you quit.",
    narrative: "A farmer leans on a hoe and studies the vines. The harvest is not instant. Look at what actually grew before you tear it up.",
  },
  {
    name: "Eight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Repetition is how the craft gets honest.",
    narrative: "An apprentice cuts the same shape again at the bench. The repetition is the teaching. Stay with the work.",
  },
  {
    name: "Nine of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "What you tended is ready to enjoy.",
    narrative: "The garden and the coin are already earned. You may enjoy what you grew. Pleasure here is the fruit, not a distraction from the work.",
  },
  {
    name: "Ten of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "A lasting house is built from small keeps.",
    narrative: "An old house holds a family, and coins are set into the arch. What lasts is the pattern you keep: care, skill, and what you pass on.",
  },
  {
    name: "Page of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Study the task before you spend on it.",
    narrative: "A student stares at a single coin as if it were a textbook. Learn the material of the task before you spend your name on it.",
  },
  {
    name: "Knight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Slow, repeated steps still arrive.",
    narrative: "The horse walks, and the coin stays in view. Slow progress is still progress when every step is aimed at the field.",
  },
  {
    name: "Queen of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Tend the practical things with warmth.",
    narrative: "She holds a coin and looks after the living things around her. Practical care is the wealth: food, time, and a place that works.",
  },
  {
    name: "King of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    line: "Steward what you have, and let it compound.",
    narrative: "He sits with a coin and a vineyard behind him. He keeps what he has by tending it, not by locking it away.",
  },
];
